global_frame: odom
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 2.0
resolution: 0.2
rolling_window: true
width: 20
height: 20

plugins:
  - {name: obstacle_layer, type: "nav2_costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "nav2_costmap_2d::InflationLayer"}

obstacle_layer:
  enabled: true
  observation_sources: scan
  scan:
    topic: /scan
    max_obstacle_height: 1.0
    clearing: true
    marking: true
    data_type: LaserScan

inflation_layer:
  inflation_radius: 0.8
  cost_scaling_factor: 3.0
