navsat_transform:
  ros__parameters:

    use_sim_time: false

    frequency: 30.0

    delay: 0.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true

    publish_filtered_gps: true

    broadcast_utm_transform: false
    broadcast_utm_transform_as_parent_frame: false
