navsat_transform:
  ros__parameters:
    use_sim_time: false
    frequency: 30.0
    delay: 0.0
    
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true

    # 关键：必须设置为 true
    publish_odom: true
    
    # 使用 datum 设置原点（使用你的初始 GPS 坐标）
    wait_for_datum: false
    # gpt: 设置为空， navsat_transform 则会默认使用第一次 GPS fix 作为 map 原点。
    # datum: []
    datum: [30.3345332, 120.0338251, 0.0, 0.0]
    # datum: [30.2749, 120.1551, 0.0, 0.0]
    # #      │________│ │________│  │   │
    # #           │         │       │   └── 初始航向（弧度），0 = 正北
    # #           │         │       └────── 初始高度（米），0 = 海平面
    # #           │         └────────────── 经度（度）
    # #           └──────────────────────── 纬度（度）

    publish_filtered_gps: true
    broadcast_utm_transform: false
    broadcast_utm_transform_as_parent_frame: false
    
    # 关键：使用 EKF 的 yaw 而不是等待 IMU 稳定
    use_odometry_yaw: false  # 使用 /odometry/filtered 的航向